using System;
using System.Collections;
using System.Collections.Generic;
using AdvancedEditorTools.Attributes;
using UnityEngine;

/// <summary>
/// An abstract class containing components needed for dialogue.
/// </summary>
public abstract class TalkableNPC : InteractableObject
{
    //Name to be displayed.
    [SerializeField, ReadOnly] public String npcName;

    //Portrait to be shown in dialogue.
    [SerializeField] public Sprite portrait;

    //JSON file generated from inky containing dialogue. 
    [SerializeField] public TextAsset defaultDialogue;

    /// <summary>
    /// Called when the script is loaded or a value is changed in the
    /// inspector (Called in the editor only).
    /// </summary>
    private void OnValidate()
    {
        npcName = gameObject.name;
    }

    /// <summary>
    /// abstract function to make sure a talk function exists.
    /// It takes in a JSON generated by inky for dialogue.
    /// </summary>
    /// <param name="dialogue">JSON file generated by inky</param>
    public abstract void Talk(TextAsset dialogue);
}
